name:  Deploy Ali baba task with Docker

on:
  push:
    branches:
      - main
      - develop # Change based on your Git Flow strategy
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build & Test React SSR
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⚡ Install Node.js & Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name:  Install Dependencies
        run: yarn install --frozen-lockfile

      - name:  Build Vite SSR App
        run: yarn build

      - name:  Run Tests
        run: yarn test

  docker:
    name:  Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name:  Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name:  Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/react-ssr:latest .

      - name:  Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/react-ssr:latest

  deploy:
    name:  Deploy to Server
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'  # Deploy only from main branch

    steps:
      - name:  Set Up SSH Connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/react-ssr:latest
            docker stop react-ssr || true
            docker rm react-ssr || true
            docker run -d --name react-ssr -p 3000:3000 ghcr.io/${{ github.repository }}/react-ssr:latest
